services:
  logbook-backend:
    image: giosava94/olog:6.0.3-email-notifier-1.2.1
    container_name: logbook-backend
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/olog-target/service-olog.jar"]
