ARG MAVEN_VERSION=3.9
ARG JAVA_VERSION=25

# ── Stage 1: build both repos ────────────────────────────────────────────────
FROM maven:${MAVEN_VERSION} AS maven-build

ARG OLOG_BRANCH=fix-notify-with-attachment-v6
ARG OLOG_VERSION=6.0.3
ARG INSTALL_EMAIL_NOTIFIER=false
ARG EMAIL_NOTIFIER_BRANCH=fix-notify-with-attachment-v6
ARG EMAIL_NOTIFIER_VERSION=1.2.1

RUN apt-get update \
    && apt-get -y install --no-install-recommends git zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 1. Clone and build phoebus-olog (multi-module).
#    "install" puts olog-api in the local Maven repo so the plugin can find it.
RUN git clone -b ${OLOG_BRANCH} --single-branch \
        https://github.com/giosava94/phoebus-olog.git

WORKDIR /phoebus-olog
RUN mvn install \
        -q \
        -DskipTests=true \
        -Dmaven.javadoc.skip=true \
        -Dmaven.source.skip=true

# 2. Produce the deployable fat-jar for the service module.
WORKDIR /phoebus-olog/service-olog
RUN mvn package \
        -q \
        -DskipTests=true \
        -Dmaven.javadoc.skip=true \
        -Dmaven.source.skip=true \
        -Pdeployable-jar \
    && cp target/service-olog-${OLOG_VERSION}.jar target/service-olog.jar

# 3. Optionally build the email notifier and inject its jar (and transitive
#    runtime deps) into the fat-jar's BOOT-INF/lib/.
#
#    Why BOOT-INF/lib/?  Spring Boot's JarLauncher puts every jar found there
#    on the application classpath automatically.  The Java SPI ServiceLoader
#    then discovers EmailNotifier via the META-INF/services file generated by
#    @AutoService at compile time.
#
#    We use "zip -ur" to ADD entries to the existing archive without touching
#    the existing MANIFEST.MF (which carries the Main-Class / Start-Class
#    attributes required for the fat-jar to be executable).
WORKDIR /
RUN if [ "${INSTALL_EMAIL_NOTIFIER}" = "true" ]; then \
      git clone -b ${EMAIL_NOTIFIER_BRANCH} --single-branch \
          https://github.com/giosava94/phoebus-olog-email-notifier-module.git; \
      \
      cd /phoebus-olog-email-notifier-module; \
      mvn package \
          -q \
          -DskipTests=true \
          -Dmaven.javadoc.skip=true; \
      \
      # Collect the plugin jar + runtime transitive deps (skip provided ones
      # that are already inside the fat-jar).
      mvn dependency:copy-dependencies \
          -q \
          -DincludeScope=runtime \
          -DexcludeScope=provided \
          -DoutputDirectory=/plugin-inject/BOOT-INF/lib; \
      cp target/olog-email-notifier-module-${EMAIL_NOTIFIER_VERSION}.jar \
         /plugin-inject/BOOT-INF/lib/; \
      \
      # Add to the fat-jar in-place, preserving all existing entries.
      cd /plugin-inject; \
      zip -ur /phoebus-olog/service-olog/target/service-olog.jar BOOT-INF/lib/; \
    fi

# ── Stage 2: minimal runtime image ───────────────────────────────────────────
FROM amazoncorretto:${JAVA_VERSION}

EXPOSE 8080
EXPOSE 8181

WORKDIR /olog-target

COPY --from=maven-build /phoebus-olog/service-olog/target/service-olog.jar .

CMD ["java", "-jar", "service-olog.jar"]
